name: widgets_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.3
  go_router: ^13.2.0
  riverpod_annotation: ^3.0.0-dev.3

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
